# Generated by Django 4.0.4 on 2022-04-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notice_number', models.CharField(max_length=10)),
                ('tender_name', models.CharField(max_length=150, unique=True)),
                ('procedure_state', models.CharField(max_length=30)),
                ('contract_type', models.CharField(max_length=40)),
                ('type_of_procurement', models.CharField(max_length=40)),
                ('estimated_value', models.FloatField()),
            ],
        ),
    ]
